export interface Team {
  id: string; // e.g., 'KC', 'LAL'
  name: string; // e.g., 'Chiefs', 'Lakers'
  city: string; // e.g., 'Kansas City', 'Los Angeles'
  abbreviation: string; // Same as id
  sport: 'NFL' | 'NBA';
  primaryColor: string; // Hex format: '#FF0000'
  secondaryColor: string; // Hex format: '#FFFFFF'
}

export const nbaTeams: Team[] = [
  // Atlantic Division
  {
    id: 'BOS',
    name: 'Celtics',
    city: 'Boston',
    abbreviation: 'BOS',
    sport: 'NBA',
    primaryColor: '#007A33',
    secondaryColor: '#BA9653',
  },
  {
    id: 'BKN',
    name: 'Nets',
    city: 'Brooklyn',
    abbreviation: 'BKN',
    sport: 'NBA',
    primaryColor: '#000000',
    secondaryColor: '#FFFFFF',
  },
  {
    id: 'NYK',
    name: 'Knicks',
    city: 'New York',
    abbreviation: 'NYK',
    sport: 'NBA',
    primaryColor: '#006BB6',
    secondaryColor: '#F58426',
  },
  {
    id: 'PHI',
    name: '76ers',
    city: 'Philadelphia',
    abbreviation: 'PHI',
    sport: 'NBA',
    primaryColor: '#006BB6',
    secondaryColor: '#ED174C',
  },
  {
    id: 'TOR',
    name: 'Raptors',
    city: 'Toronto',
    abbreviation: 'TOR',
    sport: 'NBA',
    primaryColor: '#CE1141',
    secondaryColor: '#000000',
  },

  // Central Division
  {
    id: 'CHI',
    name: 'Bulls',
    city: 'Chicago',
    abbreviation: 'CHI',
    sport: 'NBA',
    primaryColor: '#CE1141',
    secondaryColor: '#000000',
  },
  {
    id: 'CLE',
    name: 'Cavaliers',
    city: 'Cleveland',
    abbreviation: 'CLE',
    sport: 'NBA',
    primaryColor: '#6F263D',
    secondaryColor: '#FFB81C',
  },
  {
    id: 'DET',
    name: 'Pistons',
    city: 'Detroit',
    abbreviation: 'DET',
    sport: 'NBA',
    primaryColor: '#C8102E',
    secondaryColor: '#1D42BA',
  },
  {
    id: 'IND',
    name: 'Pacers',
    city: 'Indiana',
    abbreviation: 'IND',
    sport: 'NBA',
    primaryColor: '#002D62',
    secondaryColor: '#FDBB30',
  },
  {
    id: 'MIL',
    name: 'Bucks',
    city: 'Milwaukee',
    abbreviation: 'MIL',
    sport: 'NBA',
    primaryColor: '#00471B',
    secondaryColor: '#EEE1C6',
  },

  // Southeast Division
  {
    id: 'ATL',
    name: 'Hawks',
    city: 'Atlanta',
    abbreviation: 'ATL',
    sport: 'NBA',
    primaryColor: '#E03A3E',
    secondaryColor: '#C1D32F',
  },
  {
    id: 'CHA',
    name: 'Hornets',
    city: 'Charlotte',
    abbreviation: 'CHA',
    sport: 'NBA',
    primaryColor: '#1D1160',
    secondaryColor: '#00788C',
  },
  {
    id: 'MIA',
    name: 'Heat',
    city: 'Miami',
    abbreviation: 'MIA',
    sport: 'NBA',
    primaryColor: '#98002E',
    secondaryColor: '#F9A01B',
  },
  {
    id: 'ORL',
    name: 'Magic',
    city: 'Orlando',
    abbreviation: 'ORL',
    sport: 'NBA',
    primaryColor: '#0077C0',
    secondaryColor: '#C4CED4',
  },
  {
    id: 'WAS',
    name: 'Wizards',
    city: 'Washington',
    abbreviation: 'WAS',
    sport: 'NBA',
    primaryColor: '#002B5C',
    secondaryColor: '#E31837',
  },

  // Northwest Division
  {
    id: 'DEN',
    name: 'Nuggets',
    city: 'Denver',
    abbreviation: 'DEN',
    sport: 'NBA',
    primaryColor: '#0E2240',
    secondaryColor: '#FEC524',
  },
  {
    id: 'MIN',
    name: 'Timberwolves',
    city: 'Minnesota',
    abbreviation: 'MIN',
    sport: 'NBA',
    primaryColor: '#0C2340',
    secondaryColor: '#236192',
  },
  {
    id: 'OKC',
    name: 'Thunder',
    city: 'Oklahoma City',
    abbreviation: 'OKC',
    sport: 'NBA',
    primaryColor: '#007AC1',
    secondaryColor: '#EF3B24',
  },
  {
    id: 'POR',
    name: 'Trail Blazers',
    city: 'Portland',
    abbreviation: 'POR',
    sport: 'NBA',
    primaryColor: '#E03A3E',
    secondaryColor: '#000000',
  },
  {
    id: 'UTA',
    name: 'Jazz',
    city: 'Utah',
    abbreviation: 'UTA',
    sport: 'NBA',
    primaryColor: '#002B5C',
    secondaryColor: '#F9A01B',
  },

  // Pacific Division
  {
    id: 'GSW',
    name: 'Warriors',
    city: 'Golden State',
    abbreviation: 'GSW',
    sport: 'NBA',
    primaryColor: '#1D428A',
    secondaryColor: '#FFC72C',
  },
  {
    id: 'LAC',
    name: 'Clippers',
    city: 'Los Angeles',
    abbreviation: 'LAC',
    sport: 'NBA',
    primaryColor: '#C8102E',
    secondaryColor: '#1D428A',
  },
  {
    id: 'LAL',
    name: 'Lakers',
    city: 'Los Angeles',
    abbreviation: 'LAL',
    sport: 'NBA',
    primaryColor: '#552583',
    secondaryColor: '#FDB927',
  },
  {
    id: 'PHX',
    name: 'Suns',
    city: 'Phoenix',
    abbreviation: 'PHX',
    sport: 'NBA',
    primaryColor: '#1D1160',
    secondaryColor: '#E56020',
  },
  {
    id: 'SAC',
    name: 'Kings',
    city: 'Sacramento',
    abbreviation: 'SAC',
    sport: 'NBA',
    primaryColor: '#5A2D81',
    secondaryColor: '#63727A',
  },

  // Southwest Division
  {
    id: 'DAL',
    name: 'Mavericks',
    city: 'Dallas',
    abbreviation: 'DAL',
    sport: 'NBA',
    primaryColor: '#00538C',
    secondaryColor: '#002B5E',
  },
  {
    id: 'HOU',
    name: 'Rockets',
    city: 'Houston',
    abbreviation: 'HOU',
    sport: 'NBA',
    primaryColor: '#CE1141',
    secondaryColor: '#000000',
  },
  {
    id: 'MEM',
    name: 'Grizzlies',
    city: 'Memphis',
    abbreviation: 'MEM',
    sport: 'NBA',
    primaryColor: '#5D76A9',
    secondaryColor: '#12173F',
  },
  {
    id: 'NOP',
    name: 'Pelicans',
    city: 'New Orleans',
    abbreviation: 'NOP',
    sport: 'NBA',
    primaryColor: '#0C2340',
    secondaryColor: '#C8102E',
  },
  {
    id: 'SAS',
    name: 'Spurs',
    city: 'San Antonio',
    abbreviation: 'SAS',
    sport: 'NBA',
    primaryColor: '#C4CED4',
    secondaryColor: '#000000',
  },
];
