export interface Team {
  id: string; // e.g., 'KC', 'LAL'
  name: string; // e.g., 'Chiefs', 'Lakers'
  city: string; // e.g., 'Kansas City', 'Los Angeles'
  abbreviation: string; // Same as id
  sport: 'NFL' | 'NBA';
  primaryColor: string; // Hex format: '#FF0000'
  secondaryColor: string; // Hex format: '#FFFFFF'
}

export const nflTeams: Team[] = [
  // AFC East
  {
    id: 'BUF',
    name: 'Bills',
    city: 'Buffalo',
    abbreviation: 'BUF',
    sport: 'NFL',
    primaryColor: '#00338D',
    secondaryColor: '#C60C30',
  },
  {
    id: 'MIA',
    name: 'Dolphins',
    city: 'Miami',
    abbreviation: 'MIA',
    sport: 'NFL',
    primaryColor: '#008E97',
    secondaryColor: '#FC4C02',
  },
  {
    id: 'NE',
    name: 'Patriots',
    city: 'New England',
    abbreviation: 'NE',
    sport: 'NFL',
    primaryColor: '#002244',
    secondaryColor: '#C60C30',
  },
  {
    id: 'NYJ',
    name: 'Jets',
    city: 'New York',
    abbreviation: 'NYJ',
    sport: 'NFL',
    primaryColor: '#125740',
    secondaryColor: '#FFFFFF',
  },

  // AFC North
  {
    id: 'BAL',
    name: 'Ravens',
    city: 'Baltimore',
    abbreviation: 'BAL',
    sport: 'NFL',
    primaryColor: '#241773',
    secondaryColor: '#9E7C0C',
  },
  {
    id: 'CIN',
    name: 'Bengals',
    city: 'Cincinnati',
    abbreviation: 'CIN',
    sport: 'NFL',
    primaryColor: '#FB4F14',
    secondaryColor: '#000000',
  },
  {
    id: 'CLE',
    name: 'Browns',
    city: 'Cleveland',
    abbreviation: 'CLE',
    sport: 'NFL',
    primaryColor: '#311D00',
    secondaryColor: '#FF3C00',
  },
  {
    id: 'PIT',
    name: 'Steelers',
    city: 'Pittsburgh',
    abbreviation: 'PIT',
    sport: 'NFL',
    primaryColor: '#FFB612',
    secondaryColor: '#101820',
  },

  // AFC South
  {
    id: 'HOU',
    name: 'Texans',
    city: 'Houston',
    abbreviation: 'HOU',
    sport: 'NFL',
    primaryColor: '#03202F',
    secondaryColor: '#A71930',
  },
  {
    id: 'IND',
    name: 'Colts',
    city: 'Indianapolis',
    abbreviation: 'IND',
    sport: 'NFL',
    primaryColor: '#002C5F',
    secondaryColor: '#A2AAAD',
  },
  {
    id: 'JAX',
    name: 'Jaguars',
    city: 'Jacksonville',
    abbreviation: 'JAX',
    sport: 'NFL',
    primaryColor: '#101820',
    secondaryColor: '#D7A22A',
  },
  {
    id: 'TEN',
    name: 'Titans',
    city: 'Tennessee',
    abbreviation: 'TEN',
    sport: 'NFL',
    primaryColor: '#0C2340',
    secondaryColor: '#4B92DB',
  },

  // AFC West
  {
    id: 'DEN',
    name: 'Broncos',
    city: 'Denver',
    abbreviation: 'DEN',
    sport: 'NFL',
    primaryColor: '#FB4F14',
    secondaryColor: '#002244',
  },
  {
    id: 'KC',
    name: 'Chiefs',
    city: 'Kansas City',
    abbreviation: 'KC',
    sport: 'NFL',
    primaryColor: '#E31837',
    secondaryColor: '#FFB81C',
  },
  {
    id: 'LV',
    name: 'Raiders',
    city: 'Las Vegas',
    abbreviation: 'LV',
    sport: 'NFL',
    primaryColor: '#000000',
    secondaryColor: '#A5ACAF',
  },
  {
    id: 'LAC',
    name: 'Chargers',
    city: 'Los Angeles',
    abbreviation: 'LAC',
    sport: 'NFL',
    primaryColor: '#0080C6',
    secondaryColor: '#FFC20E',
  },

  // NFC East
  {
    id: 'DAL',
    name: 'Cowboys',
    city: 'Dallas',
    abbreviation: 'DAL',
    sport: 'NFL',
    primaryColor: '#041E42',
    secondaryColor: '#869397',
  },
  {
    id: 'NYG',
    name: 'Giants',
    city: 'New York',
    abbreviation: 'NYG',
    sport: 'NFL',
    primaryColor: '#0B2265',
    secondaryColor: '#A71930',
  },
  {
    id: 'PHI',
    name: 'Eagles',
    city: 'Philadelphia',
    abbreviation: 'PHI',
    sport: 'NFL',
    primaryColor: '#004C54',
    secondaryColor: '#A5ACAF',
  },
  {
    id: 'WAS',
    name: 'Commanders',
    city: 'Washington',
    abbreviation: 'WAS',
    sport: 'NFL',
    primaryColor: '#5A1414',
    secondaryColor: '#FFB612',
  },

  // NFC North
  {
    id: 'CHI',
    name: 'Bears',
    city: 'Chicago',
    abbreviation: 'CHI',
    sport: 'NFL',
    primaryColor: '#0B162A',
    secondaryColor: '#C83803',
  },
  {
    id: 'DET',
    name: 'Lions',
    city: 'Detroit',
    abbreviation: 'DET',
    sport: 'NFL',
    primaryColor: '#0076B6',
    secondaryColor: '#B0B7BC',
  },
  {
    id: 'GB',
    name: 'Packers',
    city: 'Green Bay',
    abbreviation: 'GB',
    sport: 'NFL',
    primaryColor: '#203731',
    secondaryColor: '#FFB612',
  },
  {
    id: 'MIN',
    name: 'Vikings',
    city: 'Minnesota',
    abbreviation: 'MIN',
    sport: 'NFL',
    primaryColor: '#4F2683',
    secondaryColor: '#FFC62F',
  },

  // NFC South
  {
    id: 'ATL',
    name: 'Falcons',
    city: 'Atlanta',
    abbreviation: 'ATL',
    sport: 'NFL',
    primaryColor: '#A71930',
    secondaryColor: '#000000',
  },
  {
    id: 'CAR',
    name: 'Panthers',
    city: 'Carolina',
    abbreviation: 'CAR',
    sport: 'NFL',
    primaryColor: '#0085CA',
    secondaryColor: '#101820',
  },
  {
    id: 'NO',
    name: 'Saints',
    city: 'New Orleans',
    abbreviation: 'NO',
    sport: 'NFL',
    primaryColor: '#D3BC8D',
    secondaryColor: '#101820',
  },
  {
    id: 'TB',
    name: 'Buccaneers',
    city: 'Tampa Bay',
    abbreviation: 'TB',
    sport: 'NFL',
    primaryColor: '#D50A0A',
    secondaryColor: '#34302B',
  },

  // NFC West
  {
    id: 'ARI',
    name: 'Cardinals',
    city: 'Arizona',
    abbreviation: 'ARI',
    sport: 'NFL',
    primaryColor: '#97233F',
    secondaryColor: '#000000',
  },
  {
    id: 'LAR',
    name: 'Rams',
    city: 'Los Angeles',
    abbreviation: 'LAR',
    sport: 'NFL',
    primaryColor: '#003594',
    secondaryColor: '#FFA300',
  },
  {
    id: 'SF',
    name: '49ers',
    city: 'San Francisco',
    abbreviation: 'SF',
    sport: 'NFL',
    primaryColor: '#AA0000',
    secondaryColor: '#B3995D',
  },
  {
    id: 'SEA',
    name: 'Seahawks',
    city: 'Seattle',
    abbreviation: 'SEA',
    sport: 'NFL',
    primaryColor: '#002244',
    secondaryColor: '#69BE28',
  },
];
