export interface UICategory {
  name: string;
  icon: string;
  effects: string[];
}

export const UI_CATEGORIES: Record<string, UICategory> = {
  WINS: {
    name: 'Wins',
    icon: '🏆',
    effects: [
      'fire',
      'fire_level_2',
      'fire_level_3',
      'money',
      'money_level_2',
      'money_level_3',
      'confetti',
      'celebration_level_2',
      'celebration_level_3',
      'big_w',
      'trending_up',
      'flex',
      'too_cool',
      'cool_level_2',
      'cool_level_3',
      'vibing',
      'bussin',
      'poggers',
      'to_the_moon',
      'diamond_hands',
      'diamond_hands_preview',
    ],
  },
  LOSSES: {
    name: 'Losses',
    icon: '😭',
    effects: [
      'tears',
      'tears_level_2',
      'tears_level_3',
      'skull',
      'big_l',
      'mind_blown',
      'sweating_bullets',
      'rage_quit',
      'down_bad',
      'rough_patch',
      'f_in_chat',
      'nervous',
    ],
  },
  VIBES: {
    name: 'Vibes',
    icon: '🎭',
    effects: [
      'crying_laughing',
      'no_cap',
      'clown_check',
      'sus',
      'gg_ez',
      'side_eye',
      'chefs_kiss',
      'npc_mode',
      'this_you',
      'good_vibes',
      'stay_salty',
      'no_chill',
      'sheesh',
      'ratio',
      'touch_grass',
      'main_character',
      'rizz',
      'toxic',
    ],
  },
  HYPE: {
    name: 'Hype',
    icon: '⚡',
    effects: [
      'rocket',
      'sports_level_2',
      'sports_level_3',
      'menace',
      'muscle_level_2',
      'built_different',
      'caught_4k',
      'boosted',
      'game_time',
    ],
  },
  WILDCARDS: {
    name: 'Wild',
    icon: '🎲',
    effects: [
      'sparkle',
      'sparkle_level_2',
      'sparkle_level_3',
      'dice_roll',
      'storm',
      'slot_machine',
      'bet_slip_drop',
    ],
  },
  BETTING: {
    name: 'Betting',
    icon: '💰',
    effects: ['bag_alert_preview', 'bag_alert', 'buzzer_beater_preview', 'buzzer_beater'],
  },
};
